<?php
return [

    'NEW_CONNECTION_REQUEST' => 1,
    'RE_CONNECTION_REQUEST' => 2,
    'CASUAL_CONNECTION_REQUEST' => 3,
    'CASUAL_DISCONNECTION_REQUEST' => 4,
    'RESTORATION_REQUEST' => 5,
    'TEMPORARY_DISCONNECTION_REQUEST' => 6,
    'PERMANENT_CLOSE_REQUEST' => 7,
    'ISD_FACILITIES_REQUEST' => 8,
    'NWD_FACILITIES_REQUEST' => 9,
    'NON_NWD_FACILITIES_REQUEST' => 10,
    'CENTREX_REQUEST' => 11,
    'PBX_REQUEST' => 12,
    'HOTLINE_REQUEST' => 13,
    'OUTGOING_CALL_BARING_REQUEST' => 14,
    'INCOMING_CALL_BARING_REQUEST' => 15,
    'NUMBER_CHANGE_REQUEST' => 16,
    'CLOSING_FOR_SHIFTING_REQUEST' => 17,
    'GREEN_NUMBER_REQUEST' => 18,
    'CALL_FORWARDING_REQUEST' => 19,
    'CALL_WAITING_REQUEST' => 20,
    'DO_NOT_DISTURB_REQUEST' => 21,
    'CALL_CONFERENCE_REQUEST' => 22,
    'BW_LIST_REQUEST' => 23,
    'ABSENTEE_SUBSCRIBER_REQUEST' => 24,
    'MALICIOUS_CALL_TRACE_REQUEST' => 25,
    'CONVERSION_REQUEST' => 26,
    'EISD_REQUEST' => 27,
    'UNLOCK_REQUEST' => 28,


//    'user_type' => ['User', 'Admin'],

//    JOB_REQUEST_STATUS
    'REQUEST_STATUS_PENDING'            => 1,
    'REQUEST_STATUS_AUTHENTICATE'       => 2,
    'REQUEST_STATUS_READY_TO_EXECUTE'   => 3,
    'REQUEST_STATUS_APPROVED'           => 4,
    'REQUEST_STATUS_REJECT'             => 5,

//    Number Profile Status
    'ACTIVE'    => 1,
    'INACTIVE'    => 0,

    // Network Type and Network Sub-Type value
    '171KL_NETWORK_ID' => '1',
    'TNDP_IMS_NETWORK_ID' => '2',

    '171KL_NETWORK' => '171KL Network',
    'IMS_NETWORK' => 'TNDP IMS Network',

    'CORE_JOB' => '1',
    'OLT_JOB' => '2',

    'ACTIVE_ID' => '1',
    'INACTIVE_ID' => '2',
    'NO_PBX_ID' => '3',






]



?>
